<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'PMAE_Vendor\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'PMAE_Vendor\\Soflyy\\AddonInstaller\\AddonInstaller' => $vendorDir . '/soflyy/addon-installer-sdk/src/AddonInstaller.php',
);
