<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderIniteda212c3d5897cbc525885cb5c9e0616
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PMAE_Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PMAE_Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderIniteda212c3d5897cbc525885cb5c9e0616', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PMAE_Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderIniteda212c3d5897cbc525885cb5c9e0616', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PMAE_Vendor\Composer\Autoload\ComposerStaticIniteda212c3d5897cbc525885cb5c9e0616::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
