<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'PMAE_Vendor\\Soflyy\\AddonInstaller\\' => array($vendorDir . '/soflyy/addon-installer-sdk/src'),
);
