<?php

// autoload_static.php @generated by Composer

namespace PMAE_Vendor\Composer\Autoload;

class ComposerStaticIniteda212c3d5897cbc525885cb5c9e0616
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PMAE_Vendor\\Soflyy\\AddonInstaller\\' => 34,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PMAE_Vendor\\Soflyy\\AddonInstaller\\' =>
        array (
            0 => __DIR__ . '/..' . '/soflyy/addon-installer-sdk/src',
        ),
    );

    public static $classMap = array (
        'PMAE_Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'PMAE_Vendor\\Soflyy\\AddonInstaller\\AddonInstaller' => __DIR__ . '/..' . '/soflyy/addon-installer-sdk/src/AddonInstaller.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticIniteda212c3d5897cbc525885cb5c9e0616::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticIniteda212c3d5897cbc525885cb5c9e0616::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticIniteda212c3d5897cbc525885cb5c9e0616::$classMap;

        }, null, ClassLoader::class);
    }
}
