name: 🚀 Dev Auto Deploy to WP Engine
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Getting latest code
      uses: actions/checkout@v2

    - name: 🎉 Starting deployment
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:

      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        PHP_LINT: TRUE
        flags: '-azvr --inplace --exclude=".*" --exclude-from=.deployignore'
        cache_clear: 'true'
        tpo_path: 'wp-content/themes/'
    
        dev_branch: 'master'
        dev_env: 'jdpbusines1dev'
    
        stg_branch: 'none'
        stg_env: 'none'
    
        prd_branch: 'none'
        prd_env: 'none'
